/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BusinessMetric;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessMetrics
 */
public class BusinessMetricsTest {
    private final BusinessMetrics model = new BusinessMetrics();

    /**
     * Model tests for BusinessMetrics
     */
    @Test
    public void testBusinessMetrics() {
        // TODO: test BusinessMetrics
    }

    /**
     * Test the property 'businessMetrics'
     */
    @Test
    public void businessMetricsTest() {
        // TODO: test businessMetrics
    }

}
