/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BusinessMetric
 */
public class BusinessMetricTest {
    private final BusinessMetric model = new BusinessMetric();

    /**
     * Model tests for BusinessMetric
     */
    @Test
    public void testBusinessMetric() {
        // TODO: test BusinessMetric
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'createdByToken'
     */
    @Test
    public void createdByTokenTest() {
        // TODO: test createdByToken
    }

    /**
     * Test the property 'costReportTokensWithMetadata'
     */
    @Test
    public void costReportTokensWithMetadataTest() {
        // TODO: test costReportTokensWithMetadata
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
