/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CostReportSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CostReport
 */
public class CostReportTest {
    private final CostReport model = new CostReport();

    /**
     * Model tests for CostReport
     */
    @Test
    public void testCostReport() {
        // TODO: test CostReport
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'folderToken'
     */
    @Test
    public void folderTokenTest() {
        // TODO: test folderToken
    }

    /**
     * Test the property 'savedFilterTokens'
     */
    @Test
    public void savedFilterTokensTest() {
        // TODO: test savedFilterTokens
    }

    /**
     * Test the property 'businessMetricTokensWithMetadata'
     */
    @Test
    public void businessMetricTokensWithMetadataTest() {
        // TODO: test businessMetricTokensWithMetadata
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'groupings'
     */
    @Test
    public void groupingsTest() {
        // TODO: test groupings
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'workspaceToken'
     */
    @Test
    public void workspaceTokenTest() {
        // TODO: test workspaceToken
    }

}
