/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostTeams
 */
public class PostTeamsTest {
    private final PostTeams model = new PostTeams();

    /**
     * Model tests for PostTeams
     */
    @Test
    public void testPostTeams() {
        // TODO: test PostTeams
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'workspaceTokens'
     */
    @Test
    public void workspaceTokensTest() {
        // TODO: test workspaceTokens
    }

    /**
     * Test the property 'userTokens'
     */
    @Test
    public void userTokensTest() {
        // TODO: test userTokens
    }

    /**
     * Test the property 'userEmails'
     */
    @Test
    public void userEmailsTest() {
        // TODO: test userEmails
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
