/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostReportNotifications
 */
public class PostReportNotificationsTest {
    private final PostReportNotifications model = new PostReportNotifications();

    /**
     * Model tests for PostReportNotifications
     */
    @Test
    public void testPostReportNotifications() {
        // TODO: test PostReportNotifications
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'costReportToken'
     */
    @Test
    public void costReportTokenTest() {
        // TODO: test costReportToken
    }

    /**
     * Test the property 'workspaceToken'
     */
    @Test
    public void workspaceTokenTest() {
        // TODO: test workspaceToken
    }

    /**
     * Test the property 'userTokens'
     */
    @Test
    public void userTokensTest() {
        // TODO: test userTokens
    }

    /**
     * Test the property 'recipientChannels'
     */
    @Test
    public void recipientChannelsTest() {
        // TODO: test recipientChannels
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'change'
     */
    @Test
    public void changeTest() {
        // TODO: test change
    }

}
