/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PostFolders
 */
public class PostFoldersTest {
    private final PostFolders model = new PostFolders();

    /**
     * Model tests for PostFolders
     */
    @Test
    public void testPostFolders() {
        // TODO: test PostFolders
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'parentFolderToken'
     */
    @Test
    public void parentFolderTokenTest() {
        // TODO: test parentFolderToken
    }

    /**
     * Test the property 'savedFilterTokens'
     */
    @Test
    public void savedFilterTokensTest() {
        // TODO: test savedFilterTokens
    }

    /**
     * Test the property 'workspaceToken'
     */
    @Test
    public void workspaceTokenTest() {
        // TODO: test workspaceToken
    }

}
