/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PutBusinessMetricsCostReportTokensWithMetadataInner
 */
public class PutBusinessMetricsCostReportTokensWithMetadataInnerTest {
    private final PutBusinessMetricsCostReportTokensWithMetadataInner model = new PutBusinessMetricsCostReportTokensWithMetadataInner();

    /**
     * Model tests for PutBusinessMetricsCostReportTokensWithMetadataInner
     */
    @Test
    public void testPutBusinessMetricsCostReportTokensWithMetadataInner() {
        // TODO: test PutBusinessMetricsCostReportTokensWithMetadataInner
    }

    /**
     * Test the property 'costReportToken'
     */
    @Test
    public void costReportTokenTest() {
        // TODO: test costReportToken
    }

    /**
     * Test the property 'unitScale'
     */
    @Test
    public void unitScaleTest() {
        // TODO: test unitScale
    }

}
