/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PostSegmentsReportSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PutSegments
 */
public class PutSegmentsTest {
    private final PutSegments model = new PutSegments();

    /**
     * Model tests for PutSegments
     */
    @Test
    public void testPutSegments() {
        // TODO: test PutSegments
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'trackUnallocated'
     */
    @Test
    public void trackUnallocatedTest() {
        // TODO: test trackUnallocated
    }

    /**
     * Test the property 'reportSettings'
     */
    @Test
    public void reportSettingsTest() {
        // TODO: test reportSettings
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'parentSegmentToken'
     */
    @Test
    public void parentSegmentTokenTest() {
        // TODO: test parentSegmentToken
    }

}
