/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PostCostReportsBusinessMetricTokensWithMetadataInner;
import com.konfigthis.client.model.PostCostReportsSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Create a CostReport.
 */
@ApiModel(description = "Create a CostReport.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PostCostReports {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_WORKSPACE_TOKEN = "workspace_token";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_TOKEN)
  private String workspaceToken;

  public static final String SERIALIZED_NAME_GROUPINGS = "groupings";
  @SerializedName(SERIALIZED_NAME_GROUPINGS)
  private String groupings;

  public static final String SERIALIZED_NAME_FILTER = "filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  private String filter;

  public static final String SERIALIZED_NAME_SAVED_FILTER_TOKENS = "saved_filter_tokens";
  @SerializedName(SERIALIZED_NAME_SAVED_FILTER_TOKENS)
  private List<String> savedFilterTokens = null;

  public static final String SERIALIZED_NAME_BUSINESS_METRIC_TOKENS_WITH_METADATA = "business_metric_tokens_with_metadata";
  @SerializedName(SERIALIZED_NAME_BUSINESS_METRIC_TOKENS_WITH_METADATA)
  private List<PostCostReportsBusinessMetricTokensWithMetadataInner> businessMetricTokensWithMetadata = null;

  public static final String SERIALIZED_NAME_FOLDER_TOKEN = "folder_token";
  @SerializedName(SERIALIZED_NAME_FOLDER_TOKEN)
  private String folderToken;

  public static final String SERIALIZED_NAME_SETTINGS = "settings";
  @SerializedName(SERIALIZED_NAME_SETTINGS)
  private PostCostReportsSettings settings;

  public PostCostReports() {
  }

  public PostCostReports title(String title) {
    
    
    
    
    this.title = title;
    return this;
  }

   /**
   * The title of the CostReport.
   * @return title
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The title of the CostReport.")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    
    
    
    this.title = title;
  }


  public PostCostReports workspaceToken(String workspaceToken) {
    
    
    
    
    this.workspaceToken = workspaceToken;
    return this;
  }

   /**
   * The token of the Workspace to add the Cost Report to. Ignored if &#39;folder_token&#39; is set. Required if the API token is associated with multiple Workspaces.
   * @return workspaceToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The token of the Workspace to add the Cost Report to. Ignored if 'folder_token' is set. Required if the API token is associated with multiple Workspaces.")

  public String getWorkspaceToken() {
    return workspaceToken;
  }


  public void setWorkspaceToken(String workspaceToken) {
    
    
    
    this.workspaceToken = workspaceToken;
  }


  public PostCostReports groupings(String groupings) {
    
    
    
    
    this.groupings = groupings;
    return this;
  }

   /**
   * Grouping values for aggregating costs on the report. Valid groupings: account_id, billing_account_id, charge_type, cost_category, cost_subcategory, provider, region, resource_id, service, tagged, tag:&lt;tag_value&gt;. If providing multiple groupings, join as comma separated values: groupings&#x3D;provider,service,region
   * @return groupings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Grouping values for aggregating costs on the report. Valid groupings: account_id, billing_account_id, charge_type, cost_category, cost_subcategory, provider, region, resource_id, service, tagged, tag:<tag_value>. If providing multiple groupings, join as comma separated values: groupings=provider,service,region")

  public String getGroupings() {
    return groupings;
  }


  public void setGroupings(String groupings) {
    
    
    
    this.groupings = groupings;
  }


  public PostCostReports filter(String filter) {
    
    
    
    
    this.filter = filter;
    return this;
  }

   /**
   * The filter query language to apply to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.
   * @return filter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The filter query language to apply to the CostReport. Additional documentation available at https://docs.vantage.sh/vql.")

  public String getFilter() {
    return filter;
  }


  public void setFilter(String filter) {
    
    
    
    this.filter = filter;
  }


  public PostCostReports savedFilterTokens(List<String> savedFilterTokens) {
    
    
    
    
    this.savedFilterTokens = savedFilterTokens;
    return this;
  }

  public PostCostReports addSavedFilterTokensItem(String savedFilterTokensItem) {
    if (this.savedFilterTokens == null) {
      this.savedFilterTokens = new ArrayList<>();
    }
    this.savedFilterTokens.add(savedFilterTokensItem);
    return this;
  }

   /**
   * The tokens of the SavedFilters to apply to the CostReport.
   * @return savedFilterTokens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tokens of the SavedFilters to apply to the CostReport.")

  public List<String> getSavedFilterTokens() {
    return savedFilterTokens;
  }


  public void setSavedFilterTokens(List<String> savedFilterTokens) {
    
    
    
    this.savedFilterTokens = savedFilterTokens;
  }


  public PostCostReports businessMetricTokensWithMetadata(List<PostCostReportsBusinessMetricTokensWithMetadataInner> businessMetricTokensWithMetadata) {
    
    
    
    
    this.businessMetricTokensWithMetadata = businessMetricTokensWithMetadata;
    return this;
  }

  public PostCostReports addBusinessMetricTokensWithMetadataItem(PostCostReportsBusinessMetricTokensWithMetadataInner businessMetricTokensWithMetadataItem) {
    if (this.businessMetricTokensWithMetadata == null) {
      this.businessMetricTokensWithMetadata = new ArrayList<>();
    }
    this.businessMetricTokensWithMetadata.add(businessMetricTokensWithMetadataItem);
    return this;
  }

   /**
   * The tokens for any BusinessMetrics to attach to the CostReport, and the unit scale.
   * @return businessMetricTokensWithMetadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tokens for any BusinessMetrics to attach to the CostReport, and the unit scale.")

  public List<PostCostReportsBusinessMetricTokensWithMetadataInner> getBusinessMetricTokensWithMetadata() {
    return businessMetricTokensWithMetadata;
  }


  public void setBusinessMetricTokensWithMetadata(List<PostCostReportsBusinessMetricTokensWithMetadataInner> businessMetricTokensWithMetadata) {
    
    
    
    this.businessMetricTokensWithMetadata = businessMetricTokensWithMetadata;
  }


  public PostCostReports folderToken(String folderToken) {
    
    
    
    
    this.folderToken = folderToken;
    return this;
  }

   /**
   * The token of the Folder to add the CostReport to. Determines the Workspace the report is assigned to.
   * @return folderToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The token of the Folder to add the CostReport to. Determines the Workspace the report is assigned to.")

  public String getFolderToken() {
    return folderToken;
  }


  public void setFolderToken(String folderToken) {
    
    
    
    this.folderToken = folderToken;
  }


  public PostCostReports settings(PostCostReportsSettings settings) {
    
    
    
    
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PostCostReportsSettings getSettings() {
    return settings;
  }


  public void setSettings(PostCostReportsSettings settings) {
    
    
    
    this.settings = settings;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PostCostReports instance itself
   */
  public PostCostReports putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostCostReports postCostReports = (PostCostReports) o;
    return Objects.equals(this.title, postCostReports.title) &&
        Objects.equals(this.workspaceToken, postCostReports.workspaceToken) &&
        Objects.equals(this.groupings, postCostReports.groupings) &&
        Objects.equals(this.filter, postCostReports.filter) &&
        Objects.equals(this.savedFilterTokens, postCostReports.savedFilterTokens) &&
        Objects.equals(this.businessMetricTokensWithMetadata, postCostReports.businessMetricTokensWithMetadata) &&
        Objects.equals(this.folderToken, postCostReports.folderToken) &&
        Objects.equals(this.settings, postCostReports.settings)&&
        Objects.equals(this.additionalProperties, postCostReports.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, workspaceToken, groupings, filter, savedFilterTokens, businessMetricTokensWithMetadata, folderToken, settings, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostCostReports {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    workspaceToken: ").append(toIndentedString(workspaceToken)).append("\n");
    sb.append("    groupings: ").append(toIndentedString(groupings)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    savedFilterTokens: ").append(toIndentedString(savedFilterTokens)).append("\n");
    sb.append("    businessMetricTokensWithMetadata: ").append(toIndentedString(businessMetricTokensWithMetadata)).append("\n");
    sb.append("    folderToken: ").append(toIndentedString(folderToken)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("title");
    openapiFields.add("workspace_token");
    openapiFields.add("groupings");
    openapiFields.add("filter");
    openapiFields.add("saved_filter_tokens");
    openapiFields.add("business_metric_tokens_with_metadata");
    openapiFields.add("folder_token");
    openapiFields.add("settings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("title");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PostCostReports
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PostCostReports.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostCostReports is not found in the empty JSON string", PostCostReports.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostCostReports.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("workspace_token") != null && !jsonObj.get("workspace_token").isJsonNull()) && !jsonObj.get("workspace_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workspace_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workspace_token").toString()));
      }
      if ((jsonObj.get("groupings") != null && !jsonObj.get("groupings").isJsonNull()) && !jsonObj.get("groupings").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `groupings` to be a primitive type in the JSON string but got `%s`", jsonObj.get("groupings").toString()));
      }
      if ((jsonObj.get("filter") != null && !jsonObj.get("filter").isJsonNull()) && !jsonObj.get("filter").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `filter` to be a primitive type in the JSON string but got `%s`", jsonObj.get("filter").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("saved_filter_tokens") != null && !jsonObj.get("saved_filter_tokens").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `saved_filter_tokens` to be an array in the JSON string but got `%s`", jsonObj.get("saved_filter_tokens").toString()));
      }
      if (jsonObj.get("business_metric_tokens_with_metadata") != null && !jsonObj.get("business_metric_tokens_with_metadata").isJsonNull()) {
        JsonArray jsonArraybusinessMetricTokensWithMetadata = jsonObj.getAsJsonArray("business_metric_tokens_with_metadata");
        if (jsonArraybusinessMetricTokensWithMetadata != null) {
          // ensure the json data is an array
          if (!jsonObj.get("business_metric_tokens_with_metadata").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `business_metric_tokens_with_metadata` to be an array in the JSON string but got `%s`", jsonObj.get("business_metric_tokens_with_metadata").toString()));
          }

          // validate the optional field `business_metric_tokens_with_metadata` (array)
          for (int i = 0; i < jsonArraybusinessMetricTokensWithMetadata.size(); i++) {
            PostCostReportsBusinessMetricTokensWithMetadataInner.validateJsonObject(jsonArraybusinessMetricTokensWithMetadata.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("folder_token") != null && !jsonObj.get("folder_token").isJsonNull()) && !jsonObj.get("folder_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `folder_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("folder_token").toString()));
      }
      // validate the optional field `settings`
      if (jsonObj.get("settings") != null && !jsonObj.get("settings").isJsonNull()) {
        PostCostReportsSettings.validateJsonObject(jsonObj.getAsJsonObject("settings"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostCostReports.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostCostReports' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostCostReports> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostCostReports.class));

       return (TypeAdapter<T>) new TypeAdapter<PostCostReports>() {
           @Override
           public void write(JsonWriter out, PostCostReports value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PostCostReports read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PostCostReports instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostCostReports given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostCostReports
  * @throws IOException if the JSON string is invalid with respect to PostCostReports
  */
  public static PostCostReports fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostCostReports.class);
  }

 /**
  * Convert an instance of PostCostReports to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

