/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Create a Folder for CostReports.
 */
@ApiModel(description = "Create a Folder for CostReports.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PostFolders {
  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_PARENT_FOLDER_TOKEN = "parent_folder_token";
  @SerializedName(SERIALIZED_NAME_PARENT_FOLDER_TOKEN)
  private String parentFolderToken;

  public static final String SERIALIZED_NAME_SAVED_FILTER_TOKENS = "saved_filter_tokens";
  @SerializedName(SERIALIZED_NAME_SAVED_FILTER_TOKENS)
  private List<String> savedFilterTokens = null;

  public static final String SERIALIZED_NAME_WORKSPACE_TOKEN = "workspace_token";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_TOKEN)
  private String workspaceToken;

  public PostFolders() {
  }

  public PostFolders title(String title) {
    
    
    
    
    this.title = title;
    return this;
  }

   /**
   * The title of the Folder.
   * @return title
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The title of the Folder.")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    
    
    
    this.title = title;
  }


  public PostFolders parentFolderToken(String parentFolderToken) {
    
    
    
    
    this.parentFolderToken = parentFolderToken;
    return this;
  }

   /**
   * The token of the parent Folder.
   * @return parentFolderToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The token of the parent Folder.")

  public String getParentFolderToken() {
    return parentFolderToken;
  }


  public void setParentFolderToken(String parentFolderToken) {
    
    
    
    this.parentFolderToken = parentFolderToken;
  }


  public PostFolders savedFilterTokens(List<String> savedFilterTokens) {
    
    
    
    
    this.savedFilterTokens = savedFilterTokens;
    return this;
  }

  public PostFolders addSavedFilterTokensItem(String savedFilterTokensItem) {
    if (this.savedFilterTokens == null) {
      this.savedFilterTokens = new ArrayList<>();
    }
    this.savedFilterTokens.add(savedFilterTokensItem);
    return this;
  }

   /**
   * The tokens of the SavedFilters to apply to any Cost Report contained within the Folder.
   * @return savedFilterTokens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tokens of the SavedFilters to apply to any Cost Report contained within the Folder.")

  public List<String> getSavedFilterTokens() {
    return savedFilterTokens;
  }


  public void setSavedFilterTokens(List<String> savedFilterTokens) {
    
    
    
    this.savedFilterTokens = savedFilterTokens;
  }


  public PostFolders workspaceToken(String workspaceToken) {
    
    
    
    
    this.workspaceToken = workspaceToken;
    return this;
  }

   /**
   * The token of the Workspace to add the Folder to. Ignored if &#39;parent_folder_token&#39; is set. Required if the API token is associated with multiple Workspaces.
   * @return workspaceToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The token of the Workspace to add the Folder to. Ignored if 'parent_folder_token' is set. Required if the API token is associated with multiple Workspaces.")

  public String getWorkspaceToken() {
    return workspaceToken;
  }


  public void setWorkspaceToken(String workspaceToken) {
    
    
    
    this.workspaceToken = workspaceToken;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PostFolders instance itself
   */
  public PostFolders putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostFolders postFolders = (PostFolders) o;
    return Objects.equals(this.title, postFolders.title) &&
        Objects.equals(this.parentFolderToken, postFolders.parentFolderToken) &&
        Objects.equals(this.savedFilterTokens, postFolders.savedFilterTokens) &&
        Objects.equals(this.workspaceToken, postFolders.workspaceToken)&&
        Objects.equals(this.additionalProperties, postFolders.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, parentFolderToken, savedFilterTokens, workspaceToken, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostFolders {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    parentFolderToken: ").append(toIndentedString(parentFolderToken)).append("\n");
    sb.append("    savedFilterTokens: ").append(toIndentedString(savedFilterTokens)).append("\n");
    sb.append("    workspaceToken: ").append(toIndentedString(workspaceToken)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("title");
    openapiFields.add("parent_folder_token");
    openapiFields.add("saved_filter_tokens");
    openapiFields.add("workspace_token");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("title");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PostFolders
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PostFolders.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PostFolders is not found in the empty JSON string", PostFolders.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostFolders.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("title").toString()));
      }
      if ((jsonObj.get("parent_folder_token") != null && !jsonObj.get("parent_folder_token").isJsonNull()) && !jsonObj.get("parent_folder_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `parent_folder_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parent_folder_token").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("saved_filter_tokens") != null && !jsonObj.get("saved_filter_tokens").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `saved_filter_tokens` to be an array in the JSON string but got `%s`", jsonObj.get("saved_filter_tokens").toString()));
      }
      if ((jsonObj.get("workspace_token") != null && !jsonObj.get("workspace_token").isJsonNull()) && !jsonObj.get("workspace_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `workspace_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workspace_token").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostFolders.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostFolders' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostFolders> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostFolders.class));

       return (TypeAdapter<T>) new TypeAdapter<PostFolders>() {
           @Override
           public void write(JsonWriter out, PostFolders value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PostFolders read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PostFolders instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PostFolders given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PostFolders
  * @throws IOException if the JSON string is invalid with respect to PostFolders
  */
  public static PostFolders fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostFolders.class);
  }

 /**
  * Convert an instance of PostFolders to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

