/*
 * Vantage
 * Vantage API
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@vantage.sh
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Workspace;
import com.konfigthis.client.model.Workspaces;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkspacesApi
 */
@Disabled
public class WorkspacesApiTest {

    private static WorkspacesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new WorkspacesApi(apiClient);
    }

    /**
     * Return a specific Workspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpecificWorkspaceTest() throws ApiException {
        String workspaceToken = null;
        Workspace response = api.getSpecificWorkspace(workspaceToken)
                .execute();
        // TODO: test validations
    }

    /**
     * Return all Workspaces that the current API token has access to.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listAccessibleTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        Workspaces response = api.listAccessible()
                .page(page)
                .limit(limit)
                .execute();
        // TODO: test validations
    }

}
